### PR TITLE
Set outlines of PDF

### PR DESCRIPTION
**Pull request by TD-Sky**
## TODO APIs

- [x] `PdfDocument::delete_outlines`
- [x] `PdfDocument::set_outlines`

Resolve https://github.com/messense/mupdf-rs/issues/54 .

### CODE REVIEW

**Comment by TD-Sky** [comment]
@messense `Outline.x` and `Outline.y` are different from `Destination.left` and `Destination.top`, which causes PDF viewer jumps to a wrong position in a correct page. Do you know the mapping between them? This is the last problem to be solved.

**Comment by messense** [comment]
> Do you know the mapping between them? This is the last problem to be solved.

I don't know either.

**Comment by TD-Sky** [comment]
Fixed. The key is that fitz point is in a coordinate system different from destination point of PDF.

**Comment by TD-Sky** [comment]
May you release a new version after this PR merged?

**Review by messense — APPROVED** [review]

**Comment by messense** [comment]
Published in v0.4.4.

**Pull request merged**
